### ISSUE TITLE
canBeKey 的实现探讨

### ISSUE THREAD

**Issue by LeoYuan** [zhang740/power-di#4]
https://github.com/zhang740/power-di/blob/master/lib/IocContext.ts#L373

目前我这边的场景发现在某些 babel 配置下，编译后的 class，过不了 instanceof Function 的判断，为什么不直接使用 typeof fn === 'function' 来判断是否是函数（类）？

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/97942917-4b0c7a00-1dbf-11eb-86a0-dc6020dac82b.png)

Chrome 下：
![image](https://user-images.githubusercontent.com/1195765/97943015-51025b00-1dbf-11eb-97e9-bf03782a1052.png)

Node 单测下：
![image](https://user-images.githubusercontent.com/1195765/97943123-58296900-1dbf-11eb-972d-6824b1405fef.png)

注：Chrome 和 Node 单测使用的 babel 配置确实不一样，但是我做了个小 demo 来模拟两种 babel 配置，可惜没有找到真正原因~
![image](https://user-images.githubusercontent.com/1195765/97944458-b9513c80-1dbf-11eb-9e12-4e62f45b991a.png)

**Comment by zhang740** [comment]
不太记得了。。。看上去可以替换，我改下
